site_name: RedHub
site_url: https://yunniperka.github.io/RedHub/
site_author: yunniperka

theme:
  name: material
  font:
    text: Inter
    code: Fira Code
  palette:
    - scheme: slate
      primary: custom
      accent: custom

  features:
    - navigation.sections
    - navigation.indexes
    - toc.integrate
    - navigation.tabs.sticky
    - navigation.tracking
    - content.code.copy
    - content.code.annotate
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/custom.css

nav:
  - Home: index.md
  - Windows Infrastructure:
    - Privilege Escalation:
        - Enumerating Attack Vectors: Windows/privilege-escalation/Enumerating_Attack_Vectors.md
        - Built-in-Groups Abuse: Windows/privilege-escalation/Built-in-Groups_Abuse.md
        - Excessive User Rights Abuse: Windows/privilege-escalation/Excessive_User_Rights_Abuse.md
        - File System ACLs: Windows/privilege-escalation/File_System_ACLs.md
        - Living-off-the-Land: Windows/privilege-escalation/Living_off_the_Land.md
        - Services Hijacking: Windows/privilege-escalation/Services_Hijacking.md
        - User Account Control (UAC): Windows/privilege-escalation/User_Account_Control_(UAC).md
    - Persistence: Windows/persistence.md
    - Lateral Movement: Windows/lateral-movement.md
    - Evasion: Windows/evasion.md
  - Linux:
    - Evasion: Linux/evasion.md
    - Lateral Movement: Linux/lateral-movement.md
    - Persistence: Linux/persistence.md
    - Privilege Escalation:
        - Enumerating Attack Vectors: Linux/privilege-escalation/Enumerating_Attack_Vectors.md
        - Privileged Groups: Linux/privilege-escalation/Privileged_Groups.md
        - Environment Variables Abuse: Linux/privilege-escalation/Environment_Variables_Abuse.md
        - Capabilities Abuse: Linux/privilege-escalation/Capabilities_Abuse.md
        - Programs, Jobs and Services: Linux/privilege-escalation/Programs_Jobs_and_Services.md
        - Miscellaneous Techniques: Linux/privilege-escalation/Miscellaneous_Techniques.md
  - Enterprise Environments:
    - Active Directory: AD/README.md
  - Web Security:
    - Initial Reconnaissance: Web/Initial_Reconnaissance.md
    - SQL Injection: Web/SQL_Injection.md
    - XSS: Web/XSS.md
  - Networking & Infrastructure:
    - Network Architecture: Networking/README.md
  - Modern Architecture:
    - Cloud Platforms: Cloud/README.md
    - Containers & Docker: Containers/README.md
    - Virtualization: Virtualization/README.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  generator: false

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js
  - data:text/javascript,$(document).ready(function(){var search=$('.md-search');if(search.length){var minX=240;var batCont=$('<div id="runaway-pixel-bat" class="go-right" style="position:absolute;left:'+minX+'px;top:2px;width:70px;height:50px;cursor:default;z-index:9999;user-select:none;"></div>');$('.md-header__inner').append(batCont);batCont.on('mouseenter',function(){var maxX=search.position().left-110;if(maxX<=minX){maxX=minX+100;}var randomX=Math.floor(Math.random()*(maxX-minX))+minX;var randomY=Math.floor(Math.random()*10)-5;var currentX=batCont.position().left;if(randomX<currentX){batCont.removeClass('go-right').addClass('go-left');}else{batCont.removeClass('go-left').addClass('go-right');}batCont.css({left:randomX+'px',top:randomY+'px'});});}});
